version: '3'
services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bot
    image: bot
    restart: always
    volumes:
      - /var/log/bot:/var/log/bot
    env_file:
      - .env
